### PR TITLE
Precompile

### PR DESCRIPTION
**Pull request by oliverwoodings**
- Precompile using babel down to node6
- Switch to yarn
- Replace generators with async await

@KidkArolis this fixes the issues i was seeing with uncatchable promise rejections

### CODE REVIEW

**Comment by swagatha-christie** [comment]
By analyzing the blame information on this pull request, we identified @KidkArolis to be a potential reviewer

**Comment by KidkArolis** [comment]
Noooooo! :(

Hm.. I really like babel free projects, it's so much simpler.. This adds so much machinery and indirection just to replace the `yield` keyword with `await`.

Is this to solve the issue where error leaks out of the generator?

Let me sleep on this one..

**Comment by oliverwoodings** [comment]
Yes - I'm not tied to babel though. Thought I needed but we could just use
async to gen instead which is a lot lighter.

**Comment by KidkArolis** [comment]
But you still have a compilation step. It's so cool to not need that in JS. Just run `node .` - bam.

**Comment by KidkArolis** [comment]
I guess I'm old school.

**Comment by oliverwoodings** [comment]
Have you got any suggestions for how we could fix the generator error
leaking issue?

**Comment by KidkArolis** [comment]
We don't know this fixes it, right? It would be nice to write a breaking test case. Or reread the code that breaks. I don't remember the details of the issue anymore..

Could it be fixed in creed 1.0.4? See this PR https://github.com/briancavalier/creed/pull/84

**Comment by oliverwoodings** [comment]
This pr does fix it (tested it in shelly) but yeah I'll try and make a test
case and see if the new creed fixes it.

**Pull request closed without merging**
