### PR TITLE
Make branch cache population faster

### PR DESCRIPTION
**Pull request by ralake**
This was reading the files one branch at a time, so for atom-ui, the cache population took between 5 and 6 mins which slowed us down getting things design reviewed. Introducing 5 concurrent reads took it to 1min 6 secs, and 10 concurrent reads to 42 seconds.

We weren't handling errors thrown from the async operation of tryReadingFile originally, but maybe we should do this since we are introducing concurrency?

### CODE REVIEW

**Review by bobertyy — APPROVED** [review]

**Comment by BenKandelaars** [comment]
Should all those vars be refactored to const / let? Start the process

**Comment by BenKandelaars** [comment]
Otherwise looks good

**Comment by ralake** [comment]
> Should all those vars be refactored to const / let? Start the process

Yes they probably should, was trying to leave it as untouched as possible but no reason not to really...

**Review by alanclarke — APPROVED** [review]
SICK

**Pull request merged**
